version: '3'

services:
  web:
    build: .
    command: gunicorn Project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - 8000:8000
#     depends_on:
#       - db

#   db:
#     image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     env_file:
#       - ./Project/.env
#     environment:
#       - "POSTGRES_HOST_AUTH_METHOD=trust"
  
# volumes:
#   postgres_data:
    