# Generated by Django 4.0.1 on 2022-06-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0007_remove_game_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FIR', 'Fire'), ('GRS', 'Grass'), ('WTR', 'Water'), ('BUG', 'Bug'), ('NRM', 'Normal'), ('PSN', 'Poison'), ('ELC', 'Electric'), ('GRD', 'Ground'), ('FGT', 'Fighting'), ('PSY', 'Psychic'), ('RCK', 'Rock'), ('GHT', 'Ghost'), ('ICE', 'Ice'), ('DRG', 'Dragon'), ('DRK', 'Dark'), ('STL', 'Steel'), ('FLY', 'Flying')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('attack', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('types', models.ManyToManyField(to='Games.Type')),
            ],
        ),
    ]
