# Generated by Django 4.0.1 on 2022-06-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0008_type_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='immunities',
            field=models.ManyToManyField(to='Games.Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='resistances',
            field=models.ManyToManyField(to='Games.Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='weaknesses',
            field=models.ManyToManyField(to='Games.Type'),
        ),
    ]
