# Generated by Django 4.0.1 on 2022-06-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0010_alter_type_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='immunities',
            field=models.ManyToManyField(blank=True, to='Games.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='resistances',
            field=models.ManyToManyField(blank=True, to='Games.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='weaknesses',
            field=models.ManyToManyField(blank=True, to='Games.Type'),
        ),
    ]
