# Generated by Django 4.0.1 on 2022-06-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0011_alter_type_immunities_alter_type_resistances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='immunities',
            field=models.ManyToManyField(blank=True, related_name='immunities_set', to='Games.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='resistances',
            field=models.ManyToManyField(blank=True, related_name='resistance_set', to='Games.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='weaknesses',
            field=models.ManyToManyField(blank=True, related_name='weaknesses_set', to='Games.Type'),
        ),
    ]
