# Generated by Django 4.0.1 on 2022-06-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0012_alter_type_immunities_alter_type_resistances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('FIR', 'Fire'), ('GRS', 'Grass'), ('WTR', 'Water'), ('BUG', 'Bug'), ('NRM', 'Normal'), ('PSN', 'Poison'), ('ELC', 'Electric'), ('GRD', 'Ground'), ('FGT', 'Fighting'), ('PSY', 'Psychic'), ('RCK', 'Rock'), ('GHT', 'Ghost'), ('ICE', 'Ice'), ('DRG', 'Dragon'), ('DRK', 'Dark'), ('STL', 'Steel'), ('FLY', 'Flying'), ('FAI', 'Fairy')], max_length=3),
        ),
    ]
