# Generated by Django 4.0.1 on 2022-06-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0013_alter_type_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='back_sprite',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='front_sprite',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='official_artwork',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='special_attack',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='special_defense',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(blank=True, to='Games.Type'),
        ),
    ]
