# Generated by Django 4.0.1 on 2022-06-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0014_pokemon_back_sprite_pokemon_front_sprite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='special_attack',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='special_defense',
            field=models.IntegerField(null=True),
        ),
    ]
