# Generated by Django 4.0.1 on 2022-06-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0015_alter_pokemon_attack_alter_pokemon_defense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='speed',
            field=models.IntegerField(null=True),
        ),
    ]
