# Generated by Django 4.0.1 on 2022-06-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0017_poketype_delete_type_alter_pokemon_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poketype',
            name='name',
            field=models.CharField(choices=[('fire', 'Fire'), ('grass', 'Grass'), ('water', 'Water'), ('bug', 'Bug'), ('normal', 'Normal'), ('poison', 'Poison'), ('electric', 'Electric'), ('ground', 'Ground'), ('fighting', 'Fighting'), ('psychic', 'Psychic'), ('rock', 'Rock'), ('ghost', 'Ghost'), ('ice', 'Ice'), ('dragon', 'Dragon'), ('dark', 'Dark'), ('steel', 'Steel'), ('flying', 'Flying'), ('fairy', 'Fairy')], max_length=16),
        ),
    ]
